name: 🧪 Push - Print Version
'on':
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

'jobs':
  show_version:
    runs-on: ubuntu-latest
    steps:
      - uses: Broadshield/github-action-generate-tag-name-from-maven-or-gradle@main
        id: generate-gradle
        with:
          release_branch: main
          filepath: tests/build.gradle

      - uses: Broadshield/github-action-generate-tag-name-from-maven-or-gradle@main
        id: generate-maven
        with:
          release_branch: main
          filepath: tests/pom.xml